/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health and service mode */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks, newest first (keyset pagination) */
        get: operations["listTasks"];
        put?: never;
        /** Create a task (idempotent by request_id) */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        /** Current view of a task */
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request cancellation (idempotent by request_id) */
        post: operations["cancelTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a pause (idempotent by request_id) */
        post: operations["pauseTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume a paused task (idempotent by request_id) */
        post: operations["resumeTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        /**
         * Server-sent event stream of a task (§15.2)
         * @description Each event has `id` = task_seq, `event` = the event type and `data` = an Event JSON object.
         *     Resume with `Last-Event-ID`; all events are kept in v0.2, so cursors never expire. A heartbeat
         *     comment line (`: heartbeat`) is sent every 15 s and takes no sequence number. The server closes
         *     the stream after `task_terminal`; clients stop reconnecting once they receive it.
         */
        get: operations["streamTaskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        /**
         * The pinned result of a terminal task
         * @description The result recorded when the task ended, with its outputs pinned to `(artifact_id, version, sha256)`
         *     (spec §5.6). The body is canonical JSON (sorted keys, no whitespace) and `ETag` is the quoted SHA-256
         *     of the body; clients verify it.
         */
        get: operations["getTaskResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskID"];
                artifact_id: components["parameters"]["ArtifactID"];
            };
            cookie?: never;
        };
        /**
         * Download the latest artifact version; `?version=N` is an alias of `/versions/{v}`
         * @description Only `visibility = output` artifacts are downloadable; an `internal` artifact answers exactly like a
         *     missing one (404 `artifact_not_found`). If the latest version is internal or unauthorized the answer is
         *     404, never an older version.
         */
        get: operations["getArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/artifacts/{artifact_id}/versions/{v}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskID"];
                artifact_id: components["parameters"]["ArtifactID"];
                v: number;
            };
            cookie?: never;
        };
        /** Download one pinned artifact version (canonical path, spec §15.1); only `visibility = output` versions are served */
        get: operations["getArtifactVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        /** Diagnostic timeline (§14.6); also served in diagnostic mode */
        get: operations["inspectTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        Status: {
            /** @enum {string} */
            mode: "normal" | "diagnostic" | "ownership_lost";
        };
        CreateTaskRequest: {
            request_id: string;
            /** @description Task specification passed to the worker */
            spec: Record<string, unknown>;
            /** @description Resource limits for the task */
            limits?: Record<string, unknown>;
        };
        CreateTaskResult: {
            task_id: string;
        };
        ControlRequest: {
            request_id: string;
            reason?: string;
        };
        ControlResult: {
            task_id: string;
            /** Format: int64 */
            control_version: number;
        };
        Task: {
            task_id: string;
            status: string;
            status_reason?: string;
            current_attempt_id?: string;
            /** @enum {string} */
            desired: "run" | "pause" | "cancel";
            /** Format: int64 */
            control_version: number;
            /** Format: int64 */
            applied_control_version: number;
            /** Format: int64 */
            attempts_total: number;
        };
        TaskList: {
            tasks: components["schemas"]["Task"][];
            /** @description Cursor for the next page; absent on the last page */
            next?: string;
        };
        Event: {
            /** Format: int64 */
            task_seq: number;
            attempt_id?: string;
            source: string;
            type: string;
            /** Format: int64 */
            worker_seq?: number;
            payload?: Record<string, unknown>;
            /** Format: date-time */
            ts: string;
        };
        Attempt: {
            attempt_id?: string;
            /** Format: int64 */
            attempt_no?: number;
            status?: string;
            outcome_class?: string;
            /** Format: int64 */
            exit_code?: number;
            /** Format: int64 */
            exit_signal?: number;
            /** Format: int64 */
            oom_kill_delta?: number;
            platform_killed?: boolean;
            env_id?: string;
            env_status?: string;
            cleanup_state?: string;
            /** Format: date-time */
            stopped_at?: string;
            /** Format: int64 */
            cleanup_tries?: number;
            cleanup_error?: string;
        };
        Checkpoint: {
            checkpoint_id?: string;
            step_id?: string;
            attempt_id?: string;
            /** Format: int64 */
            commit_seq?: number;
            /** Format: date-time */
            committed_at?: string;
        };
        /** @description One host-managed try of a Gateway call (audit metadata only) */
        CallTry: {
            /** Format: int64 */
            try_no: number;
            attempt_id: string;
            env_id?: string;
            /** @enum {string} */
            state: "in_flight" | "settled";
            /** @enum {string} */
            outcome?: "ok" | "retryable" | "fatal" | "unknown";
            /** Format: int64 */
            latency_ms: number;
            /**
             * Format: int64
             * @description Settled cost in micro-USD (ok tries only)
             */
            cost_micro: number;
            error?: string;
        };
        /** @description A Gateway logical call (journal entry). Metadata only — no request or response bodies, prompts or credentials. */
        Call: {
            call_id: string;
            endpoint: string;
            /** @enum {string} */
            state: "resolving" | "in_flight" | "completed" | "failed" | "unknown";
            source: string;
            first_attempt_id: string;
            /** Format: int64 */
            tries_used: number;
            /** Format: int64 */
            cost_charged_micro: number;
            upstream_request_id?: string;
            /** @description sha256 of the result blob (completed calls only) */
            result_ref?: string;
            fail_reason?: string;
            supersedes_call_id?: string;
            supersede_reason?: string;
            possible_external_duplicate: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            deadline_at: string;
            tries: components["schemas"]["CallTry"][];
        };
        /** @description An output pinned when the result was processed; version and sha256 are absent if the artifact was never saved */
        PinnedOutput: {
            artifact_id: string;
            /** Format: int64 */
            version?: number;
            sha256?: string;
        };
        Result: {
            summary: string;
            outputs: components["schemas"]["PinnedOutput"][];
        };
        Inspection: {
            task: components["schemas"]["Task"];
            attempts: components["schemas"]["Attempt"][];
            checkpoints: components["schemas"]["Checkpoint"][];
            calls: components["schemas"]["Call"][];
        };
    };
    responses: {
        /** @description Control intent accepted, or the first result of the same request replayed */
        ControlAccepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ControlResult"];
            };
        };
        /**
         * @description The artifact content, streamed from the blob store. Readable with read access; only blobs authorized
         *     to the task (`scope_blobs`) are served. `Content-Type` is the media type registered with the
         *     artifact. Active content (anything other than text/plain, text/markdown, application/json, image/png,
         *     image/jpeg and application/pdf — notably text/html and image/svg+xml) is always sent with
         *     `Content-Disposition: attachment`. The content is verified while it is sent; if it does not match the
         *     registered SHA-256 the connection is aborted, so the response is never complete.
         */
        Blob: {
            headers: {
                /** @description The quoted SHA-256 of the content (as registered) */
                ETag?: string;
                /** @description Always `nosniff` */
                "X-Content-Type-Options"?: string;
                /** @description `attachment; filename=...` for active content; absent for the inline-safe types */
                "Content-Disposition"?: string;
                [name: string]: unknown;
            };
            content: {
                "*/*": string;
            };
        };
        /** @description `task_not_found`; or `artifact_not_found`: no such artifact or version in the task, or it is `internal` (indistinguishable from missing) */
        ArtifactNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `internal`; or `blob_unavailable`: the registered content cannot be read from the blob store */
        BlobUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `invalid_request`: malformed body, missing request_id or invalid parameter; `invalid_limits` (POST /tasks): limits that can never fit the configured capacity, or max_run_time_ms not a positive integer within the server cap (omitted max_run_time_ms is filled with the default and stored with the task) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `unauthorized`: missing or wrong Bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `forbidden_host` or `forbidden_origin`: Host or Origin is not in the allowlist */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `task_not_found` */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `request_conflict`: request_id already used with different content */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description `request_conflict`; or the control is rejected by the latest task facts:
         *     `task_ended` (task is terminal), `cancel_pending` (an accepted cancel cannot be overridden),
         *     `not_paused` (resume requires a paused task)
         */
        ControlRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `internal` */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description `diagnostic_mode`, `ownership_lost`, `store_unavailable`, `contention`, or `commit_unknown`
         *     (retry with the same request_id)
         */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        TaskID: string;
        ArtifactID: string;
    };
    requestBodies: {
        Control: {
            content: {
                "application/json": components["schemas"]["ControlRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current mode */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listTasks: {
        parameters: {
            query?: {
                /** @description The `next` cursor of the previous page; omit for the first page. */
                after?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Task created, or the first result of the same request replayed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTaskResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The task */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    cancelTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Control"];
        responses: {
            200: components["responses"]["ControlAccepted"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["ControlRejected"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    pauseTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Control"];
        responses: {
            200: components["responses"]["ControlAccepted"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["ControlRejected"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    resumeTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Control"];
        responses: {
            200: components["responses"]["ControlAccepted"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["ControlRejected"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    streamTaskEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description Resume after this task_seq. Must be a non-negative integer not beyond the latest event. */
                "Last-Event-ID"?: number;
            };
            path: {
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Malformed request or `invalid_cursor` (malformed, or beyond the latest event) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    getTaskResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The pinned result */
            200: {
                headers: {
                    /** @description The quoted SHA-256 of the body */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description `task_not_found`; or `not_ready`: the task is terminal but recorded no result (failed, or cancelled before completing) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description `task_not_terminal`: the task has not ended yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    getArtifact: {
        parameters: {
            query?: {
                /** @description Alias of `/tasks/{id}/artifacts/{artifact_id}/versions/{v}` (the canonical pinned path, spec §15.1); omit for the latest version. */
                version?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["TaskID"];
                artifact_id: components["parameters"]["ArtifactID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Blob"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["ArtifactNotFound"];
            500: components["responses"]["BlobUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    getArtifactVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskID"];
                artifact_id: components["parameters"]["ArtifactID"];
                v: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Blob"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["ArtifactNotFound"];
            500: components["responses"]["BlobUnavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    inspectTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attempts with outcome, exit and OOM diagnosis, environment and cleanup state, checkpoints, and Gateway calls with their tries (task_id → attempt_id → call_id → try_no) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Inspection"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
}
